spring:
  application:
    name: emulator
  main:
    web-application-type: none
    keep-alive: true

emulator:
  gateway-url: http://localhost:8090
  interval-millis: 1000
  rooms:
    - Гостиная
    - Спальня
    - Кухня
    - Детская
